import { readFile } from 'node:fs/promises';

import { describe, expect, it } from 'vitest';

import type {
  CommandReport,
  ComposeInput,
  ComposeMetadata,
  ComposeReport,
  DiffInput,
  DiffMetadata,
  DiffReport,
  DoctorInput,
  DoctorMetadata,
  DoctorReport,
  GcInput,
  GcMetadata,
  GcReport,
  InitInput,
  InitMetadata,
  InitReport,
  InstallInput,
  InstallReport,
  InstallReportMetadata,
  ListInput,
  ListMetadata,
  ListReport,
  LockInput,
  LockMetadata,
  LockOptions,
  LockReport,
  MigrateInput,
  MigrateMetadata,
  MigrateReport,
  PackInput,
  PackMetadata,
  PackReport,
  RestoreInput,
  RestoreMetadata,
  StatusInput,
  StatusMetadata,
  StatusReport,
  SwitchInput,
  SwitchMetadata,
  SwitchReport,
  UiDangerousPermission,
  UiRequest,
  UiResponse,
  UiWriteRequest,
  UninstallInput,
  UninstallMetadata,
  UninstallReport,
  UpdateInput,
  UpdateReport,
  UpdateReportMetadata,
} from '../src/index.js';

type PublicTypes = [
  CommandReport,
  ComposeInput,
  ComposeMetadata,
  ComposeReport,
  DiffInput,
  DiffMetadata,
  DiffReport,
  DoctorInput,
  DoctorMetadata,
  DoctorReport,
  GcInput,
  GcMetadata,
  GcReport,
  InitInput,
  InitMetadata,
  InitReport,
  InstallInput,
  InstallReport,
  InstallReportMetadata,
  ListInput,
  ListMetadata,
  ListReport,
  LockMetadata,
  LockInput,
  LockOptions,
  LockReport,
  MigrateInput,
  MigrateMetadata,
  MigrateReport,
  PackInput,
  PackMetadata,
  PackReport,
  RestoreInput,
  RestoreMetadata,
  StatusInput,
  StatusMetadata,
  StatusReport,
  SwitchInput,
  SwitchMetadata,
  SwitchReport,
  UiDangerousPermission,
  UiRequest,
  UiResponse,
  UiWriteRequest,
  UninstallInput,
  UninstallMetadata,
  UninstallReport,
  UpdateInput,
  UpdateReport,
  UpdateReportMetadata,
];
void (null as unknown as PublicTypes);

describe('published CLI engine exports', () => {
  it('exports every engine entry point from the build artifact', async () => {
    const builtEntry = new URL('../dist/index.js', import.meta.url).href;
    const api = await import(builtEntry);
    const functions = [
      'composePack',
      'diffProfile',
      'initializePack',
      'installPack',
      'listProfiles',
      'runGc',
      'runDoctor',
      'migrateProfile',
      'switchProfile',
      'generateLock',
      'generateAndWriteLock',
      'packDirectory',
      'restoreProfile',
      'statusProfiles',
      'uninstallProfile',
      'updateProfile',
    ] as const;

    for (const name of functions) expect(api[name], name).toBeTypeOf('function');

    const declarations = await readFile(new URL('../dist/index.d.ts', import.meta.url), 'utf8');
    for (const name of [
      'ComposeInput',
      'ComposeMetadata',
      'ComposeReport',
      'DiffInput',
      'DiffMetadata',
      'DiffReport',
      'DoctorInput',
      'DoctorMetadata',
      'GcInput',
      'GcMetadata',
      'InitInput',
      'InitMetadata',
      'InitReport',
      'InstallInput',
      'InstallReport',
      'InstallReportMetadata',
      'ListInput',
      'ListMetadata',
      'LockOptions',
      'LockInput',
      'LockMetadata',
      'LockReport',
      'MigrateInput',
      'MigrateMetadata',
      'MigrateReport',
      'PackInput',
      'PackMetadata',
      'PackReport',
      'RestoreInput',
      'RestoreMetadata',
      'RestoreReport',
      'StatusInput',
      'StatusMetadata',
      'StatusReport',
      'SwitchInput',
      'SwitchMetadata',
      'UninstallInput',
      'UninstallMetadata',
      'UpdateInput',
      'UpdateReport',
      'UpdateReportMetadata',
      'ListReport',
      'GcReport',
      'DoctorReport',
      'MigrateReport',
      'SwitchReport',
      'RestoreReport',
      'UninstallReport',
      'UiDangerousPermission',
      'UiRequest',
      'UiResponse',
      'UiWriteRequest',
    ])
      expect(declarations, name).toContain(name);
  });
});
