export const EXIT_CODES = {
  SUCCESS: 0,
  USAGE: 2,
  ENVIRONMENT: 10,
  SOURCE_NETWORK_INTEGRITY: 20,
  USER_DECLINED: 21,
  PROFILE_CONFLICT_OR_LOCK: 22,
  DSH_SUBPROCESS_FAILURE: 23,
  POST_INSTALL_OR_ROLLBACK_FAILURE: 24,
  CONTRACT: 30,
  SECURITY: 31,
  INTERNAL: 70,
} as const;

export type ExitCode = (typeof EXIT_CODES)[keyof typeof EXIT_CODES];
